# Generated by Django 3.2.13 on 2023-03-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Придумайте логин', max_length=150, unique=True, verbose_name='Логин'),
        ),
    ]
